baseurl = "https://www.EffectOrientedProgramming.com"
languageCode = "en-us"
title = "Effect-Oriented Programming"
theme = "hugo-material-banner"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	# author = "Bruce Eckel"
	description = "Building Reliable Software with Scala3 and ZIO2"

	logo = "/images/AtomicKotlin-circle.png"
	favicon = "/images/favicon.ico?"
	banner_image = "/images/AtomicKotlinBanner.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "#18ADFB"
    	accent  = "#18ADFB"
    	header_color = "#18ADFB"
    	footer_color = "#18ADFB"
    	h1_ruler_color= "#18ADFB"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	#twitter = ""
	#github  = "EffectOrientedProgramming/WebSite"
	email   = "mindviewinc@gmail.com"

[[menu.main]]
  name   = "Atomic Kotlin"
  url    = "atomickotlin"
  weight = 10

[[menu.main]]
  name   = "Table of Contents"
  url    = "contents"
  weight = 20

[[menu.main]]
  name   = "Free Sample"
  url    = "sample"
  weight = 30

[[menu.main]]
  name   = "eBook"
  url    = "ebook"
  weight = 40

[[menu.main]]
  name   = "Print Book"
  url    = "printbook"
  weight = 50

[[menu.main]]
  name   = "Examples"
  url    = "examples"
  weight = 60

[[menu.main]]
  name   = "Exercises"
  url    = "exercises"
  weight = 70

[[menu.main]]
  name   = "Errors & Feedback"
  url    = "errorsandfeedback"
  weight = 80

[[menu.main]]
	name   = "About"
	url    = "about"
	weight = 200


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
